name:                haskell-eval-server
version:             0.1.0.0
github:              "iwashis/haskell-eval-server"
license:             BSD-3-Clause
author:              "Tomasz Brengos"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"


# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-eval-server#readme>

dependencies:
- base >= 4.7 && < 5
- network
- time 
- containers
- hint >= 0.9.0
- exceptions
- temporary
- ghc
- ghc-paths
- directory
- process
- bytestring


ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  haskell-eval-server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-eval-server
